dist: trusty
sudo: required

language: go

go:
  - "1.10"
  - "1.11"
  - "1.12"

services:
  - mysql

addons:
  postgresql: "9.6"

env:
  global:
    - MSSQLX_MYSQL_DSN="test:test@tcp(localhost:3306)/test"
    - MSSQLX_POSTGRES_DSN="user=test password=test dbname=test sslmode=disable"

before_script:
  - mysql -e "CREATE DATABASE test;"
  - mysql -u root -e "GRANT ALL ON test.* TO test@localhost IDENTIFIED BY 'test'"
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "CREATE USER "test" WITH SUPERUSER PASSWORD 'test';" -U postgres
  - go get github.com/lib/pq
  - go get github.com/mattn/go-sqlite3
  - go get github.com/go-sql-driver/mysql
  - go get github.com/jmoiron/sqlx
  - go get github.com/mattn/goveralls

script: go test -count=1 -v -race ./... && $HOME/gopath/bin/goveralls -service=travis-ci
